name: Deploy Next.js App

on:
  push:
    branches:
      - main
      - dev
      - docker
  pull_request:
    branches:
      - main
      - dev
      - docker

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      # Step 2: Create an .env file (optional, based on your variables)
      - name: Create .env file
        run: |
          echo "NEXTAUTH_SECRET=y7U3!mL9&vP@xD1#qZt$GkN5*oWfB^r8HsC2JnMfAeDhGkKjNnQrTtWwZzCcVfXj" >> .env.local
          echo "NEXT_PUBLIC_API_URL=https://megazine-api.mtktechlab.com/api" >> .env.local


      # Step 3: SSH to server and deploy
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_TAILSCALE_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
            cd /home/ubuntu/dev/kmd-megazine-frontend
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            echo "REPO_NAME=${{ github.event.repository.name }}" > .env.local
            echo "REF_NAME=${{ github.ref_name }}" >> .env.local
            echo "NEXT_PUBLIC_API_URL=https://megazine-api.mtktechlab.com/api" >> .env.local
            echo "NEXTAUTH_SECRET=y7U3!mL9&vP@xD1#qZt$GkN5*oWfB^r8HsC2JnMfAeDhGkKjNnQrTtWwZzCcVfXj" >> .env.local
            docker buildx build --platform linux/amd64 -t mtk246/${{ github.event.repository.name }}:${{ github.ref_name }} --load .
            docker-compose --env-file .env.local down || true
            docker-compose --env-file .env.local up -d
